// This file is part of Edgehog.
//
// Copyright 2026 SECO Mind Srl
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! DBus api for GeoClue service.
//!
//! You can find the GeoClue2 code at: <https://gitlab.freedesktop.org/geoclue/geoclue/>

use zbus::proxy;

/// # D-Bus interface proxy for: `org.freedesktop.GeoClue2.Manager`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.GeoClue2.Manager.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.GeoClue2.Manager",
    default_service = "org.freedesktop.GeoClue2",
    default_path = "/org/freedesktop/GeoClue2/Manager"
)]
pub(crate) trait Manager {
    /// AddAgent method
    fn add_agent(&self, id: &str) -> zbus::Result<()>;

    /// CreateClient method
    fn create_client(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// DeleteClient method
    fn delete_client(&self, client: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// GetClient method
    fn get_client(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// AvailableAccuracyLevel property
    #[zbus(property)]
    fn available_accuracy_level(&self) -> zbus::Result<u32>;

    /// InUse property
    #[zbus(property)]
    fn in_use(&self) -> zbus::Result<bool>;
}

/// # D-Bus interface proxy for: `org.freedesktop.GeoClue2.Client`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.GeoClue2.Client.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.GeoClue2.Client",
    default_service = "org.freedesktop.GeoClue2",
    default_path = "/org/freedesktop/GeoClue2/Client"
)]
pub(crate) trait Client {
    /// Start method
    fn start(&self) -> zbus::Result<()>;

    /// Stop method
    fn stop(&self) -> zbus::Result<()>;

    /// LocationUpdated signal
    #[zbus(signal)]
    fn location_updated(
        &self,
        old: zbus::zvariant::ObjectPath<'_>,
        new: zbus::zvariant::ObjectPath<'_>,
    ) -> zbus::Result<()>;

    /// Active property
    #[zbus(property)]
    fn active(&self) -> zbus::Result<bool>;

    /// DesktopId property
    #[zbus(property)]
    fn desktop_id(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_desktop_id(&self, value: &str) -> zbus::Result<()>;

    /// DistanceThreshold property
    #[zbus(property)]
    fn distance_threshold(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn set_distance_threshold(&self, value: u32) -> zbus::Result<()>;

    /// Location property
    #[zbus(property)]
    fn location(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// RequestedAccuracyLevel property
    #[zbus(property)]
    fn requested_accuracy_level(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn set_requested_accuracy_level(&self, value: u32) -> zbus::Result<()>;

    /// TimeThreshold property
    #[zbus(property)]
    fn time_threshold(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn set_time_threshold(&self, value: u32) -> zbus::Result<()>;
}

/// # D-Bus interface proxy for: `org.freedesktop.GeoClue2.Location`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.GeoClue2.Location.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.GeoClue2.Location",
    default_service = "org.freedesktop.GeoClue2",
    default_path = "/org/freedesktop/GeoClue2/Location"
)]
pub(crate) trait Location {
    /// Accuracy property
    #[zbus(property)]
    fn accuracy(&self) -> zbus::Result<f64>;

    /// Altitude property
    #[zbus(property)]
    fn altitude(&self) -> zbus::Result<f64>;

    /// Description property
    #[zbus(property)]
    fn description(&self) -> zbus::Result<String>;

    /// Heading property
    #[zbus(property)]
    fn heading(&self) -> zbus::Result<f64>;

    /// Latitude property
    #[zbus(property)]
    fn latitude(&self) -> zbus::Result<f64>;

    /// Longitude property
    #[zbus(property)]
    fn longitude(&self) -> zbus::Result<f64>;

    /// Speed property
    #[zbus(property)]
    fn speed(&self) -> zbus::Result<f64>;

    /// Timestamp property
    #[zbus(property)]
    fn timestamp(&self) -> zbus::Result<(u64, u64)>;
}

/// # D-Bus interface proxy for: `org.freedesktop.GeoClue2.Agent`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.GeoClue2.Agent.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.GeoClue2.Agent",
    default_service = "org.freedesktop.GeoClue2",
    default_path = "/org/freedesktop/GeoClue2/Agent"
)]
pub(crate) trait Agent {
    /// AuthorizeApp method
    fn authorize_app(&self, desktop_id: &str, req_accuracy_level: u32)
    -> zbus::Result<(bool, u32)>;

    /// MaxAccuracyLevel property
    #[zbus(property)]
    fn max_accuracy_level(&self) -> zbus::Result<u32>;
}
