// This file is part of Edgehog.
//
// Copyright 2026 SECO Mind Srl
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! DBus api for GeoClue service.
//!
//! You can find the GeoClue2 code at: <https://gitlab.freedesktop.org/geoclue/geoclue/>

use zbus::proxy;

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1"
)]
pub trait ModemManager1 {
    /// InhibitDevice method
    fn inhibit_device(&self, uid: &str, inhibit: bool) -> zbus::Result<()>;

    /// ReportKernelEvent method
    fn report_kernel_event(
        &self,
        properties: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// ScanDevices method
    fn scan_devices(&self) -> zbus::Result<()>;

    /// SetLogging method
    fn set_logging(&self, level: &str) -> zbus::Result<()>;

    /// Version property
    #[zbus(property)]
    fn version(&self) -> zbus::Result<String>;
}

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.Modem.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1.Modem",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1/Modem"
)]
pub trait Modem {
    /// Command method
    fn command(&self, cmd: &str, timeout: u32) -> zbus::Result<String>;

    /// CreateBearer method
    fn create_bearer(
        &self,
        properties: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// DeleteBearer method
    fn delete_bearer(&self, bearer: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// Enable method
    fn enable(&self, enable: bool) -> zbus::Result<()>;

    /// FactoryReset method
    fn factory_reset(&self, code: &str) -> zbus::Result<()>;

    /// GetCellInfo method
    fn get_cell_info(
        &self,
    ) -> zbus::Result<Vec<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>>;

    /// ListBearers method
    fn list_bearers(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// Reset method
    fn reset(&self) -> zbus::Result<()>;

    /// SetCurrentBands method
    fn set_current_bands(&self, bands: &[u32]) -> zbus::Result<()>;

    /// SetCurrentCapabilities method
    fn set_current_capabilities(&self, capabilities: u32) -> zbus::Result<()>;

    /// SetCurrentModes method
    fn set_current_modes(&self, modes: &(u32, u32)) -> zbus::Result<()>;

    /// SetPowerState method
    fn set_power_state(&self, state: u32) -> zbus::Result<()>;

    /// SetPrimarySimSlot method
    fn set_primary_sim_slot(&self, sim_slot: u32) -> zbus::Result<()>;

    /// StateChanged signal
    #[zbus(name = "state_changed", signal)]
    fn s_state_changed(&self, old: i32, new: i32, reason: u32) -> zbus::Result<()>;

    /// AccessTechnologies property
    #[zbus(property)]
    fn access_technologies(&self) -> zbus::Result<u32>;

    /// Bearers property
    #[zbus(property, object = "Bearer", object_vec)]
    fn bearers(&self);

    /// CarrierConfiguration property
    #[zbus(property)]
    fn carrier_configuration(&self) -> zbus::Result<String>;

    /// CarrierConfigurationRevision property
    #[zbus(property)]
    fn carrier_configuration_revision(&self) -> zbus::Result<String>;

    /// CurrentBands property
    #[zbus(property)]
    fn current_bands(&self) -> zbus::Result<Vec<u32>>;

    /// CurrentCapabilities property
    #[zbus(property)]
    fn current_capabilities(&self) -> zbus::Result<u32>;

    /// CurrentModes property
    #[zbus(property)]
    fn current_modes(&self) -> zbus::Result<(u32, u32)>;

    /// Device property
    #[zbus(property)]
    fn device(&self) -> zbus::Result<String>;

    /// DeviceIdentifier property
    #[zbus(property)]
    fn device_identifier(&self) -> zbus::Result<String>;

    /// Drivers property
    #[zbus(property)]
    fn drivers(&self) -> zbus::Result<Vec<String>>;

    /// EquipmentIdentifier property
    #[zbus(property)]
    fn equipment_identifier(&self) -> zbus::Result<String>;

    /// HardwareRevision property
    #[zbus(property)]
    fn hardware_revision(&self) -> zbus::Result<String>;

    /// IgnoredPorts property
    #[zbus(property)]
    fn ignored_ports(&self) -> zbus::Result<Vec<(String, u32)>>;

    /// Manufacturer property
    #[zbus(property)]
    fn manufacturer(&self) -> zbus::Result<String>;

    /// MaxActiveBearers property
    #[zbus(property)]
    fn max_active_bearers(&self) -> zbus::Result<u32>;

    /// MaxActiveMultiplexedBearers property
    #[zbus(property)]
    fn max_active_multiplexed_bearers(&self) -> zbus::Result<u32>;

    /// MaxBearers property
    #[zbus(property)]
    fn max_bearers(&self) -> zbus::Result<u32>;

    /// Model property
    #[zbus(property)]
    fn model(&self) -> zbus::Result<String>;

    /// OwnNumbers property
    #[zbus(property)]
    fn own_numbers(&self) -> zbus::Result<Vec<String>>;

    /// Physdev property
    #[zbus(property)]
    fn physdev(&self) -> zbus::Result<String>;

    /// Plugin property
    #[zbus(property)]
    fn plugin(&self) -> zbus::Result<String>;

    /// Ports property
    #[zbus(property)]
    fn ports(&self) -> zbus::Result<Vec<(String, u32)>>;

    /// PowerState property
    #[zbus(property)]
    fn power_state(&self) -> zbus::Result<u32>;

    /// PrimaryPort property
    #[zbus(property)]
    fn primary_port(&self) -> zbus::Result<String>;

    /// PrimarySimSlot property
    #[zbus(property)]
    fn primary_sim_slot(&self) -> zbus::Result<u32>;

    /// Revision property
    #[zbus(property)]
    fn revision(&self) -> zbus::Result<String>;

    /// SignalQuality property
    #[zbus(property)]
    fn signal_quality(&self) -> zbus::Result<(u32, bool)>;

    /// Sim property
    #[zbus(property)]
    fn sim(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// SimSlots property
    #[zbus(property, object = "Sim", object_vec)]
    fn sim_slots(&self);

    /// State property
    #[zbus(property)]
    fn state(&self) -> zbus::Result<i32>;

    /// StateFailedReason property
    #[zbus(property)]
    fn state_failed_reason(&self) -> zbus::Result<u32>;

    /// SupportedBands property
    #[zbus(property)]
    fn supported_bands(&self) -> zbus::Result<Vec<u32>>;

    /// SupportedCapabilities property
    #[zbus(property)]
    fn supported_capabilities(&self) -> zbus::Result<Vec<u32>>;

    /// SupportedIpFamilies property
    #[zbus(property)]
    fn supported_ip_families(&self) -> zbus::Result<u32>;

    /// SupportedModes property
    #[zbus(property)]
    fn supported_modes(&self) -> zbus::Result<Vec<(u32, u32)>>;

    /// UnlockRequired property
    #[zbus(property)]
    fn unlock_required(&self) -> zbus::Result<u32>;

    /// UnlockRetries property
    #[zbus(property)]
    fn unlock_retries(&self) -> zbus::Result<std::collections::HashMap<u32, u32>>;
}

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Sim`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.Sim.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1.Sim",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1/Sim"
)]
pub trait Sim {
    /// ChangePin method
    fn change_pin(&self, old_pin: &str, new_pin: &str) -> zbus::Result<()>;

    /// EnablePin method
    fn enable_pin(&self, pin: &str, enabled: bool) -> zbus::Result<()>;

    /// SendPin method
    fn send_pin(&self, pin: &str) -> zbus::Result<()>;

    /// SendPuk method
    fn send_puk(&self, puk: &str, pin: &str) -> zbus::Result<()>;

    /// SetPreferredNetworks method
    fn set_preferred_networks(&self, preferred_networks: &[&(&str, u32)]) -> zbus::Result<()>;

    /// Active property
    #[zbus(property)]
    fn active(&self) -> zbus::Result<bool>;

    /// Eid property
    #[zbus(property)]
    fn eid(&self) -> zbus::Result<String>;

    /// EmergencyNumbers property
    #[zbus(property)]
    fn emergency_numbers(&self) -> zbus::Result<Vec<String>>;

    /// EsimStatus property
    #[zbus(property)]
    fn esim_status(&self) -> zbus::Result<u32>;

    /// Gid1 property
    #[zbus(property)]
    fn gid1(&self) -> zbus::Result<Vec<u8>>;

    /// Gid2 property
    #[zbus(property)]
    fn gid2(&self) -> zbus::Result<Vec<u8>>;

    /// Imsi property
    #[zbus(property)]
    fn imsi(&self) -> zbus::Result<String>;

    /// OperatorIdentifier property
    #[zbus(property)]
    fn operator_identifier(&self) -> zbus::Result<String>;

    /// OperatorName property
    #[zbus(property)]
    fn operator_name(&self) -> zbus::Result<String>;

    /// PreferredNetworks property
    #[zbus(property)]
    fn preferred_networks(&self) -> zbus::Result<Vec<(String, u32)>>;

    /// Removability property
    #[zbus(property)]
    fn removability(&self) -> zbus::Result<u32>;

    /// SimIdentifier property
    #[zbus(property)]
    fn sim_identifier(&self) -> zbus::Result<String>;

    /// SimType property
    #[zbus(property)]
    fn sim_type(&self) -> zbus::Result<u32>;
}

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem.Modem3gpp`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.Modem.Modem3gpp.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1.Modem.Modem3gpp",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1/Modem/Modem3gpp"
)]
pub trait Modem3gpp {
    /// DisableFacilityLock method
    fn disable_facility_lock(&self, properties: &(u32, &str)) -> zbus::Result<()>;

    /// Register method
    fn register(&self, operator_id: &str) -> zbus::Result<()>;

    /// Scan method
    fn scan(
        &self,
    ) -> zbus::Result<Vec<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>>;

    /// SetCarrierLock method
    fn set_carrier_lock(&self, data: &[u8]) -> zbus::Result<()>;

    /// SetEpsUeModeOperation method
    fn set_eps_ue_mode_operation(&self, mode: u32) -> zbus::Result<()>;

    /// SetInitialEpsBearerSettings method
    fn set_initial_eps_bearer_settings(
        &self,
        settings: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// SetNr5gRegistrationSettings method
    fn set_nr5g_registration_settings(
        &self,
        properties: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// SetPacketServiceState method
    fn set_packet_service_state(&self, state: u32) -> zbus::Result<()>;

    /// EnabledFacilityLocks property
    #[zbus(property)]
    fn enabled_facility_locks(&self) -> zbus::Result<u32>;

    /// EpsUeModeOperation property
    #[zbus(property)]
    fn eps_ue_mode_operation(&self) -> zbus::Result<u32>;

    /// Imei property
    #[zbus(property)]
    fn imei(&self) -> zbus::Result<String>;

    /// InitialEpsBearer property
    #[zbus(property)]
    fn initial_eps_bearer(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// InitialEpsBearerSettings property
    #[zbus(property)]
    fn initial_eps_bearer_settings(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// NetworkRejection property
    #[zbus(property)]
    fn network_rejection(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Nr5gRegistrationSettings property
    #[zbus(property)]
    fn nr5g_registration_settings(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// OperatorCode property
    #[zbus(property)]
    fn operator_code(&self) -> zbus::Result<String>;

    /// OperatorName property
    #[zbus(property)]
    fn operator_name(&self) -> zbus::Result<String>;

    /// PacketServiceState property
    #[zbus(property)]
    fn packet_service_state(&self) -> zbus::Result<u32>;

    /// Pco property
    #[zbus(property)]
    fn pco(&self) -> zbus::Result<Vec<(u32, bool, Vec<u8>)>>;

    /// RegistrationState property
    #[zbus(property)]
    fn registration_state(&self) -> zbus::Result<u32>;

    /// SubscriptionState property
    #[zbus(property)]
    fn subscription_state(&self) -> zbus::Result<u32>;
}

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem.Signal`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.Modem.Signal.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1.Modem.Signal",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1/Modem/Signal"
)]
pub trait Signal {
    /// Setup method
    fn setup(&self, rate: u32) -> zbus::Result<()>;

    /// SetupThresholds method
    fn setup_thresholds(
        &self,
        settings: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// Cdma property
    #[zbus(property)]
    fn cdma(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// ErrorRateThreshold property
    #[zbus(property)]
    fn error_rate_threshold(&self) -> zbus::Result<bool>;

    /// Evdo property
    #[zbus(property)]
    fn evdo(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Gsm property
    #[zbus(property)]
    fn gsm(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Lte property
    #[zbus(property)]
    fn lte(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Nr5g property
    #[zbus(property)]
    fn nr5g(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Rate property
    #[zbus(property)]
    fn rate(&self) -> zbus::Result<u32>;

    /// RssiThreshold property
    #[zbus(property)]
    fn rssi_threshold(&self) -> zbus::Result<u32>;

    /// Umts property
    #[zbus(property)]
    fn umts(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
}

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem.Simple`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.Modem.Simple.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1.Modem.Simple",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1/Modem/Simple"
)]
pub trait Simple {
    /// Connect method
    fn connect(
        &self,
        properties: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Disconnect method
    fn disconnect(&self, bearer: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// GetStatus method
    fn get_status(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
}

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem.Location`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.Modem.Location.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1.Modem.Location",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1/Modem/Location"
)]
pub trait Location {
    /// GetLocation method
    fn get_location(
        &self,
    ) -> zbus::Result<std::collections::HashMap<u32, zbus::zvariant::OwnedValue>>;

    /// InjectAssistanceData method
    fn inject_assistance_data(&self, data: &[u8]) -> zbus::Result<()>;

    /// SetGpsRefreshRate method
    fn set_gps_refresh_rate(&self, rate: u32) -> zbus::Result<()>;

    /// SetSuplServer method
    fn set_supl_server(&self, supl: &str) -> zbus::Result<()>;

    /// Setup method
    fn setup(&self, sources: u32, signal_location: bool) -> zbus::Result<()>;

    /// AssistanceDataServers property
    #[zbus(property)]
    fn assistance_data_servers(&self) -> zbus::Result<Vec<String>>;

    /// Capabilities property
    #[zbus(property)]
    fn capabilities(&self) -> zbus::Result<u32>;

    /// Enabled property
    #[zbus(property)]
    fn enabled(&self) -> zbus::Result<u32>;

    /// GpsRefreshRate property
    #[zbus(property)]
    fn gps_refresh_rate(&self) -> zbus::Result<u32>;

    /// Location property
    #[zbus(property)]
    fn location(&self) -> zbus::Result<std::collections::HashMap<u32, zbus::zvariant::OwnedValue>>;

    /// SignalsLocation property
    #[zbus(property)]
    fn signals_location(&self) -> zbus::Result<bool>;

    /// SuplServer property
    #[zbus(property)]
    fn supl_server(&self) -> zbus::Result<String>;

    /// SupportedAssistanceData property
    #[zbus(property)]
    fn supported_assistance_data(&self) -> zbus::Result<u32>;
}

/// # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Bearer`
///
/// This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
/// Source: `org.freedesktop.ModemManager1.Bearer.xml`.
///
/// You may prefer to adapt it, instead of using it verbatim.
///
/// More information can be found in the [Writing a client proxy] section of the zbus
/// documentation.
///
///
/// [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
/// [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
#[proxy(
    interface = "org.freedesktop.ModemManager1.Bearer",
    default_service = "org.freedesktop.ModemManager1",
    default_path = "/org/freedesktop/ModemManager1/Bearer"
)]
pub trait Bearer {
    /// Connect method
    fn connect(&self) -> zbus::Result<()>;

    /// Disconnect method
    fn disconnect(&self) -> zbus::Result<()>;

    /// BearerType property
    #[zbus(property)]
    fn bearer_type(&self) -> zbus::Result<u32>;

    /// Connected property
    #[zbus(property)]
    fn connected(&self) -> zbus::Result<bool>;

    /// ConnectionError property
    #[zbus(property)]
    fn connection_error(&self) -> zbus::Result<(String, String)>;

    /// DisconnectRequest property
    #[zbus(property)]
    fn disconnect_request(&self) -> zbus::Result<bool>;

    /// Interface property
    #[zbus(property)]
    fn interface(&self) -> zbus::Result<String>;

    /// Ip4Config property
    #[zbus(property)]
    fn ip4_config(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Ip6Config property
    #[zbus(property)]
    fn ip6_config(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// IpTimeout property
    #[zbus(property)]
    fn ip_timeout(&self) -> zbus::Result<u32>;

    /// Multiplexed property
    #[zbus(property)]
    fn multiplexed(&self) -> zbus::Result<bool>;

    /// ProfileId property
    #[zbus(property)]
    fn profile_id(&self) -> zbus::Result<i32>;

    /// Properties property
    #[zbus(property)]
    fn properties(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// ReloadStatsSupported property
    #[zbus(property)]
    fn reload_stats_supported(&self) -> zbus::Result<bool>;

    /// Stats property
    #[zbus(property)]
    fn stats(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Suspended property
    #[zbus(property)]
    fn suspended(&self) -> zbus::Result<bool>;
}
