// This file is part of Edgehog.
//
// Copyright 2025 SECO Mind Srl
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `container_binds` table.
    ///
    /// (Automatically generated by Diesel.)
    container_binds (container_id, value) {
        /// The `container_id` column of the `container_binds` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `value` column of the `container_binds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_env` table.
    ///
    /// (Automatically generated by Diesel.)
    container_env (container_id, value) {
        /// The `container_id` column of the `container_env` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `value` column of the `container_env` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_missing_images` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_images (container_id) {
        /// The `container_id` column of the `container_missing_images` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `image_id` column of the `container_missing_images` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        image_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_missing_networks` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_networks (container_id, network_id) {
        /// The `container_id` column of the `container_missing_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `network_id` column of the `container_missing_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        network_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_missing_volumes` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_volumes (container_id, volume_id) {
        /// The `container_id` column of the `container_missing_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `volume_id` column of the `container_missing_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        volume_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_networks` table.
    ///
    /// (Automatically generated by Diesel.)
    container_networks (container_id, network_id) {
        /// The `container_id` column of the `container_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `network_id` column of the `container_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        network_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_port_bindings` table.
    ///
    /// (Automatically generated by Diesel.)
    container_port_bindings (container_id, port, host_ip, host_port) {
        /// The `container_id` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `port` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        port -> Text,
        /// The `host_ip` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        host_ip -> Nullable<Text>,
        /// The `host_port` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        host_port -> Nullable<Integer>,
    }
}

diesel::table! {
    /// Representation of the `container_volumes` table.
    ///
    /// (Automatically generated by Diesel.)
    container_volumes (container_id, volume_id) {
        /// The `container_id` column of the `container_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `volume_id` column of the `container_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        volume_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `containers` table.
    ///
    /// (Automatically generated by Diesel.)
    containers (id) {
        /// The `id` column of the `containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `local_id` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        local_id -> Nullable<Text>,
        /// The `image_id` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Binary>`.
        ///
        /// (Automatically generated by Diesel.)
        image_id -> Nullable<Binary>,
        /// The `status` column of the `containers` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `network_mode` column of the `containers` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        network_mode -> Text,
        /// The `hostname` column of the `containers` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        hostname -> Text,
        /// The `restart_policy` column of the `containers` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        restart_policy -> Integer,
        /// The `privileged` column of the `containers` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        privileged -> Bool,
    }
}

diesel::table! {
    /// Representation of the `deployment_containers` table.
    ///
    /// (Automatically generated by Diesel.)
    deployment_containers (deployment_id, container_id) {
        /// The `deployment_id` column of the `deployment_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        deployment_id -> Binary,
        /// The `container_id` column of the `deployment_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `deployment_missing_containers` table.
    ///
    /// (Automatically generated by Diesel.)
    deployment_missing_containers (deployment_id, container_id) {
        /// The `deployment_id` column of the `deployment_missing_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        deployment_id -> Binary,
        /// The `container_id` column of the `deployment_missing_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `deployments` table.
    ///
    /// (Automatically generated by Diesel.)
    deployments (id) {
        /// The `id` column of the `deployments` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `status` column of the `deployments` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
    }
}

diesel::table! {
    /// Representation of the `images` table.
    ///
    /// (Automatically generated by Diesel.)
    images (id) {
        /// The `id` column of the `images` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `local_id` column of the `images` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        local_id -> Nullable<Text>,
        /// The `status` column of the `images` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `reference` column of the `images` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        reference -> Text,
        /// The `registry_auth` column of the `images` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        registry_auth -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `network_driver_opts` table.
    ///
    /// (Automatically generated by Diesel.)
    network_driver_opts (network_id, name) {
        /// The `network_id` column of the `network_driver_opts` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        network_id -> Binary,
        /// The `name` column of the `network_driver_opts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `value` column of the `network_driver_opts` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `networks` table.
    ///
    /// (Automatically generated by Diesel.)
    networks (id) {
        /// The `id` column of the `networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `local_id` column of the `networks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        local_id -> Nullable<Text>,
        /// The `status` column of the `networks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `driver` column of the `networks` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        driver -> Text,
        /// The `internal` column of the `networks` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        internal -> Bool,
        /// The `enable_ipv6` column of the `networks` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enable_ipv6 -> Bool,
    }
}

diesel::table! {
    /// Representation of the `volume_driver_opts` table.
    ///
    /// (Automatically generated by Diesel.)
    volume_driver_opts (volume_id, name) {
        /// The `volume_id` column of the `volume_driver_opts` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        volume_id -> Binary,
        /// The `name` column of the `volume_driver_opts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `value` column of the `volume_driver_opts` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `volumes` table.
    ///
    /// (Automatically generated by Diesel.)
    volumes (id) {
        /// The `id` column of the `volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `status` column of the `volumes` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `driver` column of the `volumes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        driver -> Text,
    }
}

diesel::joinable!(container_binds -> containers (container_id));
diesel::joinable!(container_env -> containers (container_id));
diesel::joinable!(container_missing_images -> containers (container_id));
diesel::joinable!(container_networks -> containers (container_id));
diesel::joinable!(container_networks -> networks (network_id));
diesel::joinable!(container_port_bindings -> containers (container_id));
diesel::joinable!(container_volumes -> containers (container_id));
diesel::joinable!(containers -> images (image_id));
diesel::joinable!(deployment_containers -> containers (container_id));
diesel::joinable!(deployment_containers -> deployments (deployment_id));
diesel::joinable!(deployment_missing_containers -> deployments (deployment_id));
diesel::joinable!(network_driver_opts -> networks (network_id));

diesel::allow_tables_to_appear_in_same_query!(
    container_binds,
    container_env,
    container_missing_images,
    container_missing_networks,
    container_missing_volumes,
    container_networks,
    container_port_bindings,
    container_volumes,
    containers,
    deployment_containers,
    deployment_missing_containers,
    deployments,
    images,
    network_driver_opts,
    networks,
    volume_driver_opts,
    volumes,
);
