// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `container_add_capabilities` table.
    ///
    /// (Automatically generated by Diesel.)
    container_add_capabilities (container_id, value) {
        /// The `container_id` column of the `container_add_capabilities` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `value` column of the `container_add_capabilities` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_binds` table.
    ///
    /// (Automatically generated by Diesel.)
    container_binds (container_id, value) {
        /// The `container_id` column of the `container_binds` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `value` column of the `container_binds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_blkio_device_read_bps` table.
    ///
    /// (Automatically generated by Diesel.)
    container_blkio_device_read_bps (container_id, path) {
        /// The `container_id` column of the `container_blkio_device_read_bps` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_blkio_device_read_bps` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `rate` column of the `container_blkio_device_read_bps` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        rate -> BigInt,
    }
}

diesel::table! {
    /// Representation of the `container_blkio_device_read_iops` table.
    ///
    /// (Automatically generated by Diesel.)
    container_blkio_device_read_iops (container_id, path) {
        /// The `container_id` column of the `container_blkio_device_read_iops` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_blkio_device_read_iops` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `rate` column of the `container_blkio_device_read_iops` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        rate -> BigInt,
    }
}

diesel::table! {
    /// Representation of the `container_blkio_device_write_bps` table.
    ///
    /// (Automatically generated by Diesel.)
    container_blkio_device_write_bps (container_id, path) {
        /// The `container_id` column of the `container_blkio_device_write_bps` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_blkio_device_write_bps` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `rate` column of the `container_blkio_device_write_bps` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        rate -> BigInt,
    }
}

diesel::table! {
    /// Representation of the `container_blkio_device_write_iops` table.
    ///
    /// (Automatically generated by Diesel.)
    container_blkio_device_write_iops (container_id, path) {
        /// The `container_id` column of the `container_blkio_device_write_iops` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_blkio_device_write_iops` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `rate` column of the `container_blkio_device_write_iops` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        rate -> BigInt,
    }
}

diesel::table! {
    /// Representation of the `container_blkio_weight_device` table.
    ///
    /// (Automatically generated by Diesel.)
    container_blkio_weight_device (container_id, path) {
        /// The `container_id` column of the `container_blkio_weight_device` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_blkio_weight_device` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `weight` column of the `container_blkio_weight_device` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        weight -> Integer,
    }
}

diesel::table! {
    /// Representation of the `container_cmds` table.
    ///
    /// (Automatically generated by Diesel.)
    container_cmds (container_id, idx) {
        /// The `container_id` column of the `container_cmds` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `idx` column of the `container_cmds` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> BigInt,
        /// The `cmd` column of the `container_cmds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        cmd -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_device_cgroup_rules` table.
    ///
    /// (Automatically generated by Diesel.)
    container_device_cgroup_rules (container_id, rule) {
        /// The `container_id` column of the `container_device_cgroup_rules` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `rule` column of the `container_device_cgroup_rules` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        rule -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_device_mappings` table.
    ///
    /// (Automatically generated by Diesel.)
    container_device_mappings (container_id, device_mapping_id) {
        /// The `container_id` column of the `container_device_mappings` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `device_mapping_id` column of the `container_device_mappings` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        device_mapping_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_device_requests` table.
    ///
    /// (Automatically generated by Diesel.)
    container_device_requests (container_id, device_request_id) {
        /// The `container_id` column of the `container_device_requests` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `device_request_id` column of the `container_device_requests` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        device_request_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_dns` table.
    ///
    /// (Automatically generated by Diesel.)
    container_dns (container_id, dns) {
        /// The `container_id` column of the `container_dns` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `dns` column of the `container_dns` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        dns -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_dns_options` table.
    ///
    /// (Automatically generated by Diesel.)
    container_dns_options (container_id, dns_option) {
        /// The `container_id` column of the `container_dns_options` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `dns_option` column of the `container_dns_options` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        dns_option -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_dns_search` table.
    ///
    /// (Automatically generated by Diesel.)
    container_dns_search (container_id, dns_search) {
        /// The `container_id` column of the `container_dns_search` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `dns_search` column of the `container_dns_search` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        dns_search -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_drop_capabilities` table.
    ///
    /// (Automatically generated by Diesel.)
    container_drop_capabilities (container_id, value) {
        /// The `container_id` column of the `container_drop_capabilities` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `value` column of the `container_drop_capabilities` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_entrypoints` table.
    ///
    /// (Automatically generated by Diesel.)
    container_entrypoints (container_id, idx) {
        /// The `container_id` column of the `container_entrypoints` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `idx` column of the `container_entrypoints` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> BigInt,
        /// The `cmd` column of the `container_entrypoints` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        cmd -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_env` table.
    ///
    /// (Automatically generated by Diesel.)
    container_env (container_id, value) {
        /// The `container_id` column of the `container_env` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `value` column of the `container_env` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_exposed_ports` table.
    ///
    /// (Automatically generated by Diesel.)
    container_exposed_ports (container_id, port) {
        /// The `container_id` column of the `container_exposed_ports` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `port` column of the `container_exposed_ports` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        port -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_extra_hosts` table.
    ///
    /// (Automatically generated by Diesel.)
    container_extra_hosts (container_id, value) {
        /// The `container_id` column of the `container_extra_hosts` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `value` column of the `container_extra_hosts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_group_add` table.
    ///
    /// (Automatically generated by Diesel.)
    container_group_add (container_id, group_add) {
        /// The `container_id` column of the `container_group_add` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `group_add` column of the `container_group_add` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        group_add -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_healthcheck_test` table.
    ///
    /// (Automatically generated by Diesel.)
    container_healthcheck_test (container_id, idx) {
        /// The `container_id` column of the `container_healthcheck_test` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `idx` column of the `container_healthcheck_test` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> BigInt,
        /// The `cmd` column of the `container_healthcheck_test` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        cmd -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_labels` table.
    ///
    /// (Automatically generated by Diesel.)
    container_labels (container_id, key) {
        /// The `container_id` column of the `container_labels` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `key` column of the `container_labels` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `value` column of the `container_labels` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_log_config` table.
    ///
    /// (Automatically generated by Diesel.)
    container_log_config (container_id, key) {
        /// The `container_id` column of the `container_log_config` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `key` column of the `container_log_config` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `value` column of the `container_log_config` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_masked_paths` table.
    ///
    /// (Automatically generated by Diesel.)
    container_masked_paths (container_id, path) {
        /// The `container_id` column of the `container_masked_paths` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_masked_paths` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_missing_device_mappings` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_device_mappings (container_id, device_mapping_id) {
        /// The `container_id` column of the `container_missing_device_mappings` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `device_mapping_id` column of the `container_missing_device_mappings` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        device_mapping_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_missing_device_requests` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_device_requests (container_id, device_request_id) {
        /// The `container_id` column of the `container_missing_device_requests` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `device_request_id` column of the `container_missing_device_requests` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        device_request_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_missing_images` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_images (container_id) {
        /// The `container_id` column of the `container_missing_images` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `image_id` column of the `container_missing_images` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        image_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_missing_networks` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_networks (container_id, network_id) {
        /// The `container_id` column of the `container_missing_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `network_id` column of the `container_missing_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        network_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_missing_volumes` table.
    ///
    /// (Automatically generated by Diesel.)
    container_missing_volumes (container_id, volume_id) {
        /// The `container_id` column of the `container_missing_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `volume_id` column of the `container_missing_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        volume_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_networks` table.
    ///
    /// (Automatically generated by Diesel.)
    container_networks (container_id, network_id) {
        /// The `container_id` column of the `container_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `network_id` column of the `container_networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        network_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `container_port_bindings` table.
    ///
    /// (Automatically generated by Diesel.)
    container_port_bindings (container_id, port, idx) {
        /// The `container_id` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `port` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        port -> Text,
        /// The `idx` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> BigInt,
        /// The `host_ip` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        host_ip -> Nullable<Text>,
        /// The `host_port` column of the `container_port_bindings` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        host_port -> Nullable<Integer>,
    }
}

diesel::table! {
    /// Representation of the `container_readonly_paths` table.
    ///
    /// (Automatically generated by Diesel.)
    container_readonly_paths (container_id, path) {
        /// The `container_id` column of the `container_readonly_paths` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_readonly_paths` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_securityopts` table.
    ///
    /// (Automatically generated by Diesel.)
    container_securityopts (container_id, opt) {
        /// The `container_id` column of the `container_securityopts` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `opt` column of the `container_securityopts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        opt -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_storage_options` table.
    ///
    /// (Automatically generated by Diesel.)
    container_storage_options (container_id, name) {
        /// The `container_id` column of the `container_storage_options` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `name` column of the `container_storage_options` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `value` column of the `container_storage_options` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_sysctls` table.
    ///
    /// (Automatically generated by Diesel.)
    container_sysctls (container_id, key) {
        /// The `container_id` column of the `container_sysctls` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `key` column of the `container_sysctls` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `value` column of the `container_sysctls` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_tmpfs` table.
    ///
    /// (Automatically generated by Diesel.)
    container_tmpfs (container_id, path) {
        /// The `container_id` column of the `container_tmpfs` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `path` column of the `container_tmpfs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `options` column of the `container_tmpfs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        options -> Text,
    }
}

diesel::table! {
    /// Representation of the `container_ulimits` table.
    ///
    /// (Automatically generated by Diesel.)
    container_ulimits (container_id, name) {
        /// The `container_id` column of the `container_ulimits` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `name` column of the `container_ulimits` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `soft` column of the `container_ulimits` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        soft -> Integer,
        /// The `hard` column of the `container_ulimits` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        hard -> Integer,
    }
}

diesel::table! {
    /// Representation of the `container_volumes` table.
    ///
    /// (Automatically generated by Diesel.)
    container_volumes (container_id, volume_id) {
        /// The `container_id` column of the `container_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `volume_id` column of the `container_volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        volume_id -> Binary,
    }
}

diesel::table! {
    /// Representation of the `containers` table.
    ///
    /// (Automatically generated by Diesel.)
    containers (id) {
        /// The `id` column of the `containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `local_id` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        local_id -> Nullable<Text>,
        /// The `image_id` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Binary>`.
        ///
        /// (Automatically generated by Diesel.)
        image_id -> Nullable<Binary>,
        /// The `status` column of the `containers` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `hostname` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        hostname -> Nullable<Text>,
        /// The `cpu_period` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        cpu_period -> Nullable<BigInt>,
        /// The `cpu_quota` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        cpu_quota -> Nullable<BigInt>,
        /// The `cpu_realtime_period` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        cpu_realtime_period -> Nullable<BigInt>,
        /// The `cpu_realtime_runtime` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        cpu_realtime_runtime -> Nullable<BigInt>,
        /// The `memory` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        memory -> Nullable<BigInt>,
        /// The `memory_reservation` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        memory_reservation -> Nullable<BigInt>,
        /// The `memory_swap` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        memory_swap -> Nullable<BigInt>,
        /// The `memory_swappiness` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<SmallInt>`.
        ///
        /// (Automatically generated by Diesel.)
        memory_swappiness -> Nullable<SmallInt>,
        /// The `volume_driver` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        volume_driver -> Nullable<Text>,
        /// The `domainname` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        domainname -> Nullable<Text>,
        /// The `user` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user -> Nullable<Text>,
        /// The `health_check_interval` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        health_check_interval -> Nullable<BigInt>,
        /// The `health_check_timeout` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        health_check_timeout -> Nullable<BigInt>,
        /// The `health_check_retries` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        health_check_retries -> Nullable<Integer>,
        /// The `health_check_start_period` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        health_check_start_period -> Nullable<BigInt>,
        /// The `health_check_start_interval` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        health_check_start_interval -> Nullable<BigInt>,
        /// The `working_dir` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        working_dir -> Nullable<Text>,
        /// The `network_disabled` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        network_disabled -> Nullable<Bool>,
        /// The `stop_signal` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        stop_signal -> Nullable<Text>,
        /// The `stop_timeout` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        stop_timeout -> Nullable<Integer>,
        /// The `restart_policy_maximum_retry_count` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        restart_policy_maximum_retry_count -> Nullable<Integer>,
        /// The `cpu_shares` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        cpu_shares -> Nullable<Integer>,
        /// The `cpuset_cpus` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        cpuset_cpus -> Nullable<Text>,
        /// The `auto_remove` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        auto_remove -> Nullable<Bool>,
        /// The `cgroupns_mode` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<SmallInt>`.
        ///
        /// (Automatically generated by Diesel.)
        cgroupns_mode -> Nullable<SmallInt>,
        /// The `ipc_mode` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        ipc_mode -> Nullable<Text>,
        /// The `oom_score_adj` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        oom_score_adj -> Nullable<Integer>,
        /// The `userns_mode` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        userns_mode -> Nullable<Text>,
        /// The `shm_size` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        shm_size -> Nullable<BigInt>,
        /// The `log_type` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        log_type -> Nullable<Text>,
        /// The `blkio_weight` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<SmallInt>`.
        ///
        /// (Automatically generated by Diesel.)
        blkio_weight -> Nullable<SmallInt>,
        /// The `pid_mode` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        pid_mode -> Nullable<Text>,
        /// The `runtime` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        runtime -> Nullable<Text>,
        /// The `network_mode` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        network_mode -> Nullable<Text>,
        /// The `restart_policy` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        restart_policy -> Nullable<Integer>,
        /// The `read_only_rootfs` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        read_only_rootfs -> Nullable<Bool>,
        /// The `privileged` column of the `containers` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        privileged -> Nullable<Bool>,
    }
}

diesel::table! {
    /// Representation of the `deployment_containers` table.
    ///
    /// (Automatically generated by Diesel.)
    deployment_containers (deployment_id, container_id) {
        /// The `deployment_id` column of the `deployment_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        deployment_id -> Binary,
        /// The `container_id` column of the `deployment_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `idx` column of the `deployment_containers` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> BigInt,
    }
}

diesel::table! {
    /// Representation of the `deployment_missing_containers` table.
    ///
    /// (Automatically generated by Diesel.)
    deployment_missing_containers (deployment_id, container_id) {
        /// The `deployment_id` column of the `deployment_missing_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        deployment_id -> Binary,
        /// The `container_id` column of the `deployment_missing_containers` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        container_id -> Binary,
        /// The `idx` column of the `deployment_missing_containers` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> BigInt,
    }
}

diesel::table! {
    /// Representation of the `deployments` table.
    ///
    /// (Automatically generated by Diesel.)
    deployments (id) {
        /// The `id` column of the `deployments` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `status` column of the `deployments` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
    }
}

diesel::table! {
    /// Representation of the `device_mappings` table.
    ///
    /// (Automatically generated by Diesel.)
    device_mappings (id) {
        /// The `id` column of the `device_mappings` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `status` column of the `device_mappings` table.
        ///
        /// Its SQL type is `SmallInt`.
        ///
        /// (Automatically generated by Diesel.)
        status -> SmallInt,
        /// The `path_on_host` column of the `device_mappings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path_on_host -> Text,
        /// The `path_in_container` column of the `device_mappings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path_in_container -> Text,
        /// The `cgroup_permissions` column of the `device_mappings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        cgroup_permissions -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `device_requests` table.
    ///
    /// (Automatically generated by Diesel.)
    device_requests (id) {
        /// The `id` column of the `device_requests` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `status` column of the `device_requests` table.
        ///
        /// Its SQL type is `SmallInt`.
        ///
        /// (Automatically generated by Diesel.)
        status -> SmallInt,
        /// The `driver` column of the `device_requests` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        driver -> Nullable<Text>,
        /// The `count` column of the `device_requests` table.
        ///
        /// Its SQL type is `Nullable<BigInt>`.
        ///
        /// (Automatically generated by Diesel.)
        count -> Nullable<BigInt>,
    }
}

diesel::table! {
    /// Representation of the `device_requests_capabilities` table.
    ///
    /// (Automatically generated by Diesel.)
    device_requests_capabilities (device_request_id, idx, capability) {
        /// The `device_request_id` column of the `device_requests_capabilities` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        device_request_id -> Binary,
        /// The `idx` column of the `device_requests_capabilities` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> Integer,
        /// The `capability` column of the `device_requests_capabilities` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        capability -> Text,
    }
}

diesel::table! {
    /// Representation of the `device_requests_device_ids` table.
    ///
    /// (Automatically generated by Diesel.)
    device_requests_device_ids (device_request_id, device_id) {
        /// The `device_request_id` column of the `device_requests_device_ids` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        device_request_id -> Binary,
        /// The `device_id` column of the `device_requests_device_ids` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        device_id -> Text,
    }
}

diesel::table! {
    /// Representation of the `device_requests_options` table.
    ///
    /// (Automatically generated by Diesel.)
    device_requests_options (device_request_id, name) {
        /// The `device_request_id` column of the `device_requests_options` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        device_request_id -> Binary,
        /// The `name` column of the `device_requests_options` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `value` column of the `device_requests_options` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `images` table.
    ///
    /// (Automatically generated by Diesel.)
    images (id) {
        /// The `id` column of the `images` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `local_id` column of the `images` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        local_id -> Nullable<Text>,
        /// The `status` column of the `images` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `reference` column of the `images` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        reference -> Text,
        /// The `registry_auth` column of the `images` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        registry_auth -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `network_driver_opts` table.
    ///
    /// (Automatically generated by Diesel.)
    network_driver_opts (network_id, name) {
        /// The `network_id` column of the `network_driver_opts` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        network_id -> Binary,
        /// The `name` column of the `network_driver_opts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `value` column of the `network_driver_opts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `networks` table.
    ///
    /// (Automatically generated by Diesel.)
    networks (id) {
        /// The `id` column of the `networks` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `local_id` column of the `networks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        local_id -> Nullable<Text>,
        /// The `status` column of the `networks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `driver` column of the `networks` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        driver -> Text,
        /// The `internal` column of the `networks` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        internal -> Bool,
        /// The `enable_ipv6` column of the `networks` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enable_ipv6 -> Bool,
    }
}

diesel::table! {
    /// Representation of the `volume_driver_opts` table.
    ///
    /// (Automatically generated by Diesel.)
    volume_driver_opts (volume_id, name) {
        /// The `volume_id` column of the `volume_driver_opts` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        volume_id -> Binary,
        /// The `name` column of the `volume_driver_opts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `value` column of the `volume_driver_opts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `volumes` table.
    ///
    /// (Automatically generated by Diesel.)
    volumes (id) {
        /// The `id` column of the `volumes` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `status` column of the `volumes` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `driver` column of the `volumes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        driver -> Text,
    }
}

diesel::joinable!(container_add_capabilities -> containers (container_id));
diesel::joinable!(container_binds -> containers (container_id));
diesel::joinable!(container_blkio_device_read_bps -> containers (container_id));
diesel::joinable!(container_blkio_device_read_iops -> containers (container_id));
diesel::joinable!(container_blkio_device_write_bps -> containers (container_id));
diesel::joinable!(container_blkio_device_write_iops -> containers (container_id));
diesel::joinable!(container_blkio_weight_device -> containers (container_id));
diesel::joinable!(container_cmds -> containers (container_id));
diesel::joinable!(container_device_cgroup_rules -> containers (container_id));
diesel::joinable!(container_device_mappings -> containers (container_id));
diesel::joinable!(container_device_mappings -> device_mappings (device_mapping_id));
diesel::joinable!(container_device_requests -> containers (container_id));
diesel::joinable!(container_device_requests -> device_requests (device_request_id));
diesel::joinable!(container_dns -> containers (container_id));
diesel::joinable!(container_dns_options -> containers (container_id));
diesel::joinable!(container_dns_search -> containers (container_id));
diesel::joinable!(container_drop_capabilities -> containers (container_id));
diesel::joinable!(container_entrypoints -> containers (container_id));
diesel::joinable!(container_env -> containers (container_id));
diesel::joinable!(container_exposed_ports -> containers (container_id));
diesel::joinable!(container_extra_hosts -> containers (container_id));
diesel::joinable!(container_group_add -> containers (container_id));
diesel::joinable!(container_healthcheck_test -> containers (container_id));
diesel::joinable!(container_labels -> containers (container_id));
diesel::joinable!(container_log_config -> containers (container_id));
diesel::joinable!(container_masked_paths -> containers (container_id));
diesel::joinable!(container_missing_device_mappings -> containers (container_id));
diesel::joinable!(container_missing_device_requests -> containers (container_id));
diesel::joinable!(container_missing_images -> containers (container_id));
diesel::joinable!(container_missing_networks -> containers (container_id));
diesel::joinable!(container_missing_volumes -> containers (container_id));
diesel::joinable!(container_networks -> containers (container_id));
diesel::joinable!(container_networks -> networks (network_id));
diesel::joinable!(container_port_bindings -> containers (container_id));
diesel::joinable!(container_readonly_paths -> containers (container_id));
diesel::joinable!(container_securityopts -> containers (container_id));
diesel::joinable!(container_storage_options -> containers (container_id));
diesel::joinable!(container_sysctls -> containers (container_id));
diesel::joinable!(container_tmpfs -> containers (container_id));
diesel::joinable!(container_ulimits -> containers (container_id));
diesel::joinable!(container_volumes -> containers (container_id));
diesel::joinable!(container_volumes -> volumes (volume_id));
diesel::joinable!(containers -> images (image_id));
diesel::joinable!(deployment_containers -> containers (container_id));
diesel::joinable!(deployment_containers -> deployments (deployment_id));
diesel::joinable!(deployment_missing_containers -> deployments (deployment_id));
diesel::joinable!(device_requests_capabilities -> device_requests (device_request_id));
diesel::joinable!(device_requests_device_ids -> device_requests (device_request_id));
diesel::joinable!(device_requests_options -> device_requests (device_request_id));
diesel::joinable!(network_driver_opts -> networks (network_id));
diesel::joinable!(volume_driver_opts -> volumes (volume_id));

diesel::allow_tables_to_appear_in_same_query!(
    container_add_capabilities,
    container_binds,
    container_blkio_device_read_bps,
    container_blkio_device_read_iops,
    container_blkio_device_write_bps,
    container_blkio_device_write_iops,
    container_blkio_weight_device,
    container_cmds,
    container_device_cgroup_rules,
    container_device_mappings,
    container_device_requests,
    container_dns,
    container_dns_options,
    container_dns_search,
    container_drop_capabilities,
    container_entrypoints,
    container_env,
    container_exposed_ports,
    container_extra_hosts,
    container_group_add,
    container_healthcheck_test,
    container_labels,
    container_log_config,
    container_masked_paths,
    container_missing_device_mappings,
    container_missing_device_requests,
    container_missing_images,
    container_missing_networks,
    container_missing_volumes,
    container_networks,
    container_port_bindings,
    container_readonly_paths,
    container_securityopts,
    container_storage_options,
    container_sysctls,
    container_tmpfs,
    container_ulimits,
    container_volumes,
    containers,
    deployment_containers,
    deployment_missing_containers,
    deployments,
    device_mappings,
    device_requests,
    device_requests_capabilities,
    device_requests_device_ids,
    device_requests_options,
    images,
    network_driver_opts,
    networks,
    volume_driver_opts,
    volumes,
);
