// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `job_queue` table.
    ///
    /// (Automatically generated by Diesel.)
    job_queue (id, job_type) {
        /// The `id` column of the `job_queue` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Binary,
        /// The `job_type` column of the `job_queue` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        job_type -> Integer,
        /// The `status` column of the `job_queue` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Integer,
        /// The `version` column of the `job_queue` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
        /// The `tag` column of the `job_queue` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        tag -> Integer,
        /// The `data` column of the `job_queue` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Binary,
        /// The `created_at` column of the `job_queue` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Integer,
    }
}
