// This file is part of Edgehog.
//
// Copyright 2026 SECO Mind Srl
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Http {
    #[prost(bytes = "vec", tag = "1")]
    pub request_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "http::Message", tags = "2, 3")]
    pub message: ::core::option::Option<http::Message>,
}
/// Nested message and enum types in `Http`.
pub mod http {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Request {
        #[prost(string, tag = "1")]
        pub path: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub method: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub query_string: ::prost::alloc::string::String,
        #[prost(map = "string, string", tag = "4")]
        pub headers: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            ::prost::alloc::string::String,
        >,
        #[prost(bytes = "vec", tag = "5")]
        pub body: ::prost::alloc::vec::Vec<u8>,
        #[prost(uint32, tag = "6")]
        pub port: u32,
        #[prost(string, optional, tag = "7")]
        pub host: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Response {
        #[prost(uint32, tag = "1")]
        pub status_code: u32,
        #[prost(map = "string, string", tag = "2")]
        pub headers: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            ::prost::alloc::string::String,
        >,
        #[prost(bytes = "vec", tag = "3")]
        pub body: ::prost::alloc::vec::Vec<u8>,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "2")]
        Request(Request),
        #[prost(message, tag = "3")]
        Response(Response),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Https {
    #[prost(bytes = "vec", tag = "1")]
    pub request_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "https::Message", tags = "3, 4")]
    pub message: ::core::option::Option<https::Message>,
}
/// Nested message and enum types in `Https`.
pub mod https {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "3")]
        Request(super::http::Request),
        #[prost(message, tag = "4")]
        Response(super::http::Response),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WebSocket {
    #[prost(bytes = "vec", tag = "1")]
    pub socket_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "web_socket::Message", tags = "2, 3, 4, 5, 6")]
    pub message: ::core::option::Option<web_socket::Message>,
}
/// Nested message and enum types in `WebSocket`.
pub mod web_socket {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Close {
        #[prost(uint32, tag = "1")]
        pub code: u32,
        #[prost(string, tag = "2")]
        pub reason: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        #[prost(string, tag = "2")]
        Text(::prost::alloc::string::String),
        #[prost(bytes, tag = "3")]
        Binary(::prost::alloc::vec::Vec<u8>),
        #[prost(bytes, tag = "4")]
        Ping(::prost::alloc::vec::Vec<u8>),
        #[prost(bytes, tag = "5")]
        Pong(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "6")]
        Close(Close),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(oneof = "message::Protocol", tags = "1, 2, 3")]
    pub protocol: ::core::option::Option<message::Protocol>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Protocol {
        #[prost(message, tag = "1")]
        Http(super::Http),
        #[prost(message, tag = "2")]
        Ws(super::WebSocket),
        #[prost(message, tag = "3")]
        Https(super::Https),
    }
}
