# This file is part of Edgehog.
#
# Copyright 2025, 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.runtime]
file = "src/schema/runtime.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
with_docs = true

[print_schema.runtime.filter]
only_tables = [
  "job_queue",
]

[print_schema.containers]
file = "src/schema/containers.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
with_docs = true

[print_schema.containers.filter]
only_tables = [
  "container_add_capabilities",
  "container_binds",
  "container_device_mappings",
  "container_device_requests",
  "container_drop_capabilities",
  "container_env",
  "container_extra_hosts",
  "container_missing_device_mappings",
  "container_missing_device_requests",
  "container_missing_images",
  "container_missing_networks",
  "container_missing_volumes",
  "container_networks",
  "container_port_bindings",
  "container_storage_options",
  "container_tmpfs",
  "container_volumes",
  "containers",
  "deployment_containers",
  "deployments",
  "device_mappings",
  "device_requests",
  "device_requests_capabilities",
  "device_requests_device_ids",
  "device_requests_options",
  "images",
  "network_driver_opts",
  "networks",
  "volume_driver_opts",
  "volumes",
]
